package com.tong.beau.util;

public enum CCPMUserAuthority {
	VIEW_REPORT,
	UPDATE_REPORT,
	DELETE_REPORT,
	VIEW_INCIDENT,
	UPDATE_INCIDENT,
	DELETE_INCIDENT,
	VIEW_DATASET,
	UPDATE_DATASET,
	DELETE_DATASET,
	VIEW_USER_MANAGEMENT,
	UPDATE_USER_MANAGEMENT,
	DELETE_USER_MANAGEMENT;
}
